Котляров Николай, 308 группа

Task 1:

In [4]:
import numpy as np
arr = np.random.random((10,3))
print(arr)

[[0.536903   0.40226681 0.06862737]
 [0.14620389 0.69658666 0.59997768]
 [0.4037809  0.14717574 0.3224453 ]
 [0.78628298 0.30745523 0.23675402]
 [0.71030258 0.23267867 0.68106493]
 [0.88907287 0.69566305 0.40758581]
 [0.99106352 0.41129102 0.7758745 ]
 [0.45367896 0.83302324 0.82400332]
 [0.37169072 0.63815004 0.56062338]
 [0.87248181 0.87798559 0.23714969]]


In [16]:
print(arr[np.arange(10),np.argmin(abs(arr - 0.5), axis = 1)])

[0.536903   0.59997768 0.4037809  0.30745523 0.68106493 0.40758581
 0.41129102 0.45367896 0.56062338 0.23714969]


Task 2:

In [18]:
arr = np.random.random((6,6))
print(arr)

[[0.40803609 0.82966263 0.26018859 0.94623245 0.08580301 0.24139272]
 [0.57921466 0.23477349 0.17973266 0.99341686 0.85624642 0.82976086]
 [0.76433957 0.24611617 0.54700876 0.04315687 0.83060225 0.03752426]
 [0.80061557 0.45837651 0.07783158 0.40114142 0.28258938 0.49250927]
 [0.59880006 0.9437002  0.99553259 0.05985277 0.63343958 0.6397259 ]
 [0.93554819 0.52282712 0.12554297 0.88807451 0.19219636 0.16635687]]


In [21]:
print(np.sum(arr,axis = 1)/np.min(arr,axis=0))

[ 6.79183909 15.64548446 31.71910334 58.23090194 45.11556056 75.43242721]


Task 3:

In [23]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

mask = x == 0
print(np.max(x[1:][mask[:-1]]))

5


Task 4:

In [24]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])

print(x + np.bincount(i, None, len(x)))

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


Task 5:

In [69]:
def New_kmeans(obs, k, iter = 20, thresh = 1e-05) :
    vec = New_whiten(obs)
    (M, N) = vec.shape
    codebook = vec[0:k]    
    distortion1 = 0
    distortion2 = 0
    b = np.arange(M)
    distortion2 += np.linalg.norm(vec[k:]-codebook[k-1], None)**2 #norm    
    
    while (abs(distortion2 - distortion1) > thresh) :
        distortion1 = distortion2
        distortion2 = 0
        for i in range(M):
            b[i] = np.argmin(np.linalg.norm(codebook-vec[i], None, 1, True))
        matr = np.hstack((vec, np.reshape(b, (M, 1))))
        for i in range(k):
            codebook[i] = np.vstack(row for row in matr if row[-1] == i).mean(axis=0)[:-1]
            distortion2 += np.linalg.norm((np.vstack(row for row in matr if row[-1] == i))[:, :-1] - codebook[i], None)**2 
            
    return np.append(codebook, distortion2)

def vec_to_cluster(obs, codebook) :
    vec = New_whiten(obs)
    (M, N) = vec.shape
    b = np.arange(M)
    for i in range(M) :
        b[i] = np.argmin(np.linalg.norm(codebook-vec[i], None, 1, True)) 
    
    return  np.hstack((vec, np.reshape(b, (M, 1))))

from scipy.cluster.vq import whiten
def New_whiten(obs):
    (M, N) = obs.shape
    for i in range(N):
        obs[:, i] = obs[:, i]/np.std(obs[:, i])
    return obs   

o = np.array([[-8.4, 4.3, 1.5],
              [1.9, 7.5, 5.55],
              [6.6, 2.5, 1.6,],
              [2.2, 3.4, 7.8]])

print(whiten(o))
print(New_whiten(o))

[[-1.52571314  2.27999636  0.5589988 ]
 [ 0.34510178  3.97673784  2.06829555]
 [ 1.19877461  1.32557928  0.59626538]
 [ 0.39959154  1.80278782  2.90679375]]
[[-1.52571314  2.27999636  0.5589988 ]
 [ 0.34510178  3.97673784  2.06829555]
 [ 1.19877461  1.32557928  0.59626538]
 [ 0.39959154  1.80278782  2.90679375]]


Task 6: не получилось сделать